Repository dbt-labs/dbt-common, pull requests merged in 2024-09, with the labels that each got.

#183 Add Behavior Flag Framework
  .changes/unreleased/Features-20240808-194933.yaml
  .gitignore
  dbt_common/__about__.py
  dbt_common/behavior_flags.py
  dbt_common/events/types.proto
  dbt_common/events/types.py
  dbt_common/events/types_pb2.py
  pyproject.toml
  tests/unit/conftest.py
  tests/unit/test_behavior_flags.py
  tests/unit/test_events.py
  tests/unit/utils.py
Labels: cla:yes

#188 bump dbt-common version to 1.8 for release
  dbt_common/__about__.py
Labels: Skip Changelog, cla:yes

#187 Add Type Annotations in jinja and semver Code
  dbt_common/clients/jinja.py
  dbt_common/exceptions/jinja.py
  dbt_common/record.py
  dbt_common/semver.py
  tests/unit/test_behavior_flags.py
  tests/unit/test_diff.py
  tests/unit/test_functions.py
  tests/unit/test_semver.py
  tests/unit/test_utils.py
Labels: Skip Changelog, tidy_first, cla:yes

#193 Update behavior deprecation flags to be behavior change flags
  dbt_common/behavior_flags.py
  dbt_common/events/types.proto
  dbt_common/events/types.py
  dbt_common/events/types_pb2.py
  tests/unit/test_behavior_flags.py
  tests/unit/test_events.py
Labels: Skip Changelog, cla:yes

#192 Add "object" mergebehavior to MergeBehavior processing
  .changes/unreleased/Features-20240918-114903.yaml
  dbt_common/contracts/config/base.py
  tests/unit/test_model_config.py
Labels: cla:yes

#194 bump version to 1.9.0
  dbt_common/__about__.py
Labels: Skip Changelog, cla:yes

#195 uncapitalize Code
  dbt_common/exceptions/base.py
Labels: Skip Changelog, tidy_first, cla:yes

#197 restrict behavior flags to firing a warning only the first time
  .changes/unreleased/Fixes-20240920-165607.yaml
  dbt_common/behavior_flags.py
  tests/unit/test_behavior_flags.py
Labels: cla:yes

#198 Bump to version 1.10.0 for Release
  dbt_common/__about__.py
Labels: Skip Changelog, cla:yes
