Repository dbt-labs/dbt-common, pull requests merged in 2024-05, with the labels that each got.

#119 pin agate
  .changes/unreleased/Dependencies-20240425-112704.yaml
  pyproject.toml
Labels: cla:yes

#122 move agate pin back to 1.7
  .changes/unreleased/Dependencies-20240425-112704.yaml
  pyproject.toml
Labels: cla:yes

#121 bump patch version to 1.0.3
  dbt_common/__about__.py
Labels: Skip Changelog, Skip Core Testing, cla:yes

#120 chore: update pathspec upper version limitation
  .changes/unreleased/Dependencies-20240501-140032.yaml
  pyproject.toml
Labels: cla:yes

#125 Add msgpack mixin to dbtClassMixin
  .changes/unreleased/Features-20240506-170058.yaml
  dbt_common/contracts/config/properties.py
  dbt_common/dataclass_schema.py
  tests/unit/test_dataclass_schema.py
  third-party-stubs/mashumaro/jsonschema/models.pyi
  third-party-stubs/mashumaro/mixins/dict.pyi
Labels: cla:yes

#127 Bump project version to 1.0.4 for release
  dbt_common/__about__.py
Labels: Skip Changelog, cla:yes

#129 Add documentation of the design and intent of the record/replay mechanism.
  dbt_common/record.py
  docs/README.md
  docs/guides/record_replay.md
Labels: Skip Changelog, cla:yes

#134 [TIDY FIRST] Remove conditional `typing_extensions` import for python < 3.8
  dbt_common/events/base_types.py
Labels: Skip Changelog, tidy_first, cla:yes

#130 Create a print Event to replace the print usage in dbt-core
  .changes/unreleased/Features-20240515-161106.yaml
  dbt_common/events/logger.py
  dbt_common/events/types.proto
  dbt_common/events/types.py
  dbt_common/events/types_pb2.py
  tests/unit/events/test_logger.py
  tests/unit/test_events.py
Labels: cla:yes

#136 move test_semver to common
  tests/unit/test_semver.py
Labels: cla:yes

#137 bump for release
  dbt_common/__about__.py
Labels: Skip Changelog, cla:yes

#135 add query recording options
  .changes/unreleased/Under the Hood-20240528-110518.yaml
  dbt_common/record.py
  docs/guides/record_replay.md
  tests/unit/test_record.py
Labels: cla:yes

#141 Move `StatsItem`, `StatsDict`, `TableMetadata` to `dbt-common`
  .changes/unreleased/Under the Hood-20240529-143154.yaml
  .gitignore
  dbt_common/contracts/metadata.py
Labels: cla:yes

#142 rename var
  dbt_common/record.py
  docs/guides/record_replay.md
  tests/unit/test_record.py
Labels: Skip Changelog, cla:yes

#143 minor version bump
  dbt_common/__about__.py
Labels: Skip Changelog, cla:yes
