Repository dbt-labs/dbt-common, pull requests merged in 2024-07, with the labels that each got.

#160 bump version to 1.5.0
  dbt_common/__about__.py
Labels: Skip Changelog, cla:yes

#162 Improve Type Annotations Coverage
  dbt_common/context.py
  dbt_common/dataclass_schema.py
  dbt_common/exceptions/base.py
  dbt_common/helper_types.py
  dbt_common/record.py
  dbt_common/semver.py
  dbt_common/utils/casting.py
  dbt_common/utils/executor.py
  dbt_common/utils/jinja.py
  tests/unit/test_agate_helper.py
  tests/unit/test_connection_retries.py
  tests/unit/test_contextvars.py
  tests/unit/test_contracts_util.py
  tests/unit/test_core_dbt_utils.py
  tests/unit/test_diff.py
  tests/unit/test_event_handler.py
  tests/unit/test_helper_types.py
  tests/unit/test_invocation_context.py
  tests/unit/test_jinja.py
  tests/unit/test_model_config.py
  tests/unit/test_proto_events.py
  tests/unit/test_record.py
  tests/unit/test_semver.py
  tests/unit/test_system_client.py
  tests/unit/test_ui.py
  tests/unit/test_utils.py
Labels: Skip Changelog, cla:yes

#164 conditionally import deepdiff
  dbt_common/record.py
Labels: Skip Changelog, cla:yes

#166 Fix case-insensitive env vars for Windows
  .changes/unreleased/Fixes-20240715-205355.yaml
  dbt_common/context.py
  pyproject.toml
  tests/unit/test_invocation_context.py
Labels: cla:yes

#167 minor version bump to 1.6.0
  dbt_common/__about__.py
Labels: Skip Changelog, cla:yes

#169 Add group property to records. Correct filter on file records.
  .changes/unreleased/Under the Hood-20240716-125753.yaml
  dbt_common/clients/system.py
  dbt_common/record.py
  docs/guides/record_replay.md
Labels: cla:yes

#172 Update to minor version 1.7
  dbt_common/__about__.py
Labels: Skip Changelog, cla:yes

#156 Add some type annotations
  dbt_common/contracts/config/base.py
  dbt_common/invocation.py
  dbt_common/semver.py
  dbt_common/utils/casting.py
  dbt_common/utils/connection.py
  dbt_common/utils/jinja.py
Labels: Skip Changelog, tidy_first, cla:yes
