Repository dbt-labs/dbt-common, pull requests merged in 2024-04, with the labels that each got.

#102 Update version to 1.0.0!!!
  dbt_common/__about__.py
Labels: Skip Changelog

#106 Bump version to 1.0.1
  dbt_common/__about__.py
Labels: Skip Changelog

#115 [tidy first] move exception import to top of functions.py
  dbt_common/events/functions.py
Labels: Skip Changelog, tidy_first

#105 Update dbt-core dependency of dbt-common for testing
  .github/workflows/ci_dbt_core_testing.yml
Labels: Skip Changelog, cla:yes

#117 Bump to version 1.0.2
  dbt_common/__about__.py
Labels: Skip Changelog, cla:yes

#118 Pin `macos` test runners to `macos-12`
  .github/workflows/ci_dbt_core_testing.yml
Labels: Skip Changelog, cla:yes
